import type { Metadata } from "next";
import "./globals.css";
import DynamicNavbar from '@/components/dynamic-navbar';
import AuthStatus from "../components/authStatus"
import SessionProviderWrapper from '@/utils/sessionProviderWrapper'

import { UserRoleProvider } from './context/userRoleContext';


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <SessionProviderWrapper>
          <UserRoleProvider>
            <html lang="en">
            <body className="antialiased">
            
              <DynamicNavbar />
            
            {/* <AuthStatus /> */}
          
            {children}
            </body>
            </html>
          </UserRoleProvider>
        </SessionProviderWrapper>
    );
}
